<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>DBTextWorks Thesaurus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(Term|ScopeNote|DateCreated|DateChanged|'Term FR'|'Int Instruments')</string>
			<key>name</key>
			<string>Generic header</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(RT)</string>
			<key>name</key>
			<string>Related</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(BT)</string>
			<key>name</key>
			<string>Broader</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(NT)</string>
			<key>name</key>
			<string>Narrower</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(UF)</string>
			<key>name</key>
			<string>Use for</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(Use)</string>
			<key>name</key>
			<string>Use</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ssraw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(^ID) (\d+)</string>
			<key>name</key>
			<string>ID number</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(;)</string>
			<key>name</key>
			<string>Line continuation</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\$)$</string>
			<key>name</key>
			<string>End of term</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.dbtext</string>
	<key>uuid</key>
	<string>c4e7bc1a-d782-4559-87a4-f3373178fe63</string>
</dict>
</plist>
